build: Find gpgme using Meson
Meson supports this since 0.51 so we can now use this.

This also fixes incorrect parsing of versions like 1.13.1-unknown:

	Traceback (most recent call last):
	  File "/home/jtojnar/Projects/almanah/build-aux/gpg_check_version.py", line 39, in <module>
	    if check_version(gpg_version, accepted_version, is_gpgme):
	  File "/home/jtojnar/Projects/almanah/build-aux/gpg_check_version.py", line 19, in check_version
	    return int(gpg_major) == int(acc_major) and int(gpg_minor) >= int(acc_minor) and int(gpg_micro) >= int(acc_micro)
	ValueError: invalid literal for int() with base 10: '1-unknown'